### ISSUE TITLE
implement "set timer" command

### ISSUE THREAD

**Issue by jeremyandrews** [jeremyandrews/kakaia#7]
In order for Kakaia to have a purpose, it needs to recognize spoken commands. Doing some research, the most complete solution in Rust seems to be [Snips NLU](https://github.com/snipsco/snips-nlu-rs). Integrate and add support for a set timer command.

**Comment by jeremyandrews** [comment]
Initial attempt at defining a reasonably flexible command:

```yaml
# setTimer intent
---
type: intent
name: setTimer
slots: 
 - name: duration
   entity: snips/duration
utterances: 
 - Set the timer [duration](for five minutes)
 - Please set a [duration](three hour) timer
 - Sta`rt a timer of [duration](half an hour)
 - Can you start a timer [duration](for eight minutes)
 - Initiate a timer [duration](for thirteen minutes)
```
